### PR TITLE
(Issue #58) Do not hard code java path in backup class.

### PR DESCRIPTION
**Pull request by mkrakowitzer**
Since the javahome parameter is required. It makes sense to use the
path ${javahome}/bin/java.

### CODE REVIEW

**Comment by ffrank** [comment]
Good idea.

Concerning tests, I'd prefer two see this covered more distinctly:
1. the existing specs should just make sure the default values are applied (from `params`)
2. a new test should be added that _only_ concerns itself with the `java` path that ends up being used, given the parameter value

**Comment by nibalizer** [comment]
:+1:

**Comment by mkrakowitzer** [comment]
The javahome is actually a required parameter. It used to be set
```puppet
$javahome,
```
But I think because that effects the puppet module scoring, I made it
```
$javahome = undef,
```
I think I should perhaps make it
```puppet
$javahome = 'UNSET'
```
and fail if it is it equals 'UNSET'.

Alternatively add support for the puppetlabs-java module and enable that by default, with an option to turn it off.

I generally find Java pretty hard to manage, Each of my developers have there own opinions what Java version to install and whether it should be from the OS package management tools or directly from oracle. With regards to stash, I kind of feel I want them to explicitly set this and not automatically decide for them.

Atlassians tools generally tend to prefer Oracle JDK/JRE over Open JDK/JRE. To enable this for RHEL, you need to get into managing subscriptions to RHEL channels and so on. I am also not sure how good the supprot is for Oracle java using the https://forge.puppetlabs.com/puppetlabs/java#limitations

To make things even worse as per Atlassian
- Support for Java 7 is deprecated, and will be removed in Stash 4.0. Which should released soon.

To me Java is such huge animal it should be managed by the user with a stash role/profile and they should explicitly set what they want to use when calling the module.

Let me know your thoughts.

**Comment by ffrank** [comment]
On 03/25/2015 11:49 AM, Merritt Krakowitzer wrote:

> I think I should perhaps make it
> 
> $javahome = 'UNSET'
> 
> and fail if it is it equals 'UNSET'.

If you feel compelled to perform such antics to please the arcane
mechanisms that power the Forge, it might be those that need fixing or
adjusting. /cc @ryancoleman

> Alternatively add support for the puppetlabs-java module and enable
> that by default, with an option to turn it off.

That _would_ make the module more self-contained, yes. Good UX.

On the other hand, if we pull this specific Java module in as a
dependency, some users might feel patronized, or will outright have to
forego this module if they cannot have puppetlabs-java in their
environment. I myself am rather sensitive about such things, bordering
on the irrational.

**Comment by ryancoleman** [comment]
Almost certainly you did not mean to cc @ryancoleman on this. No worries, but you may want to figure out who to cc.

**Comment by ffrank** [comment]
Right. Sorry! I was thinking of @ryanycoleman.

**Comment by ryanycoleman** [comment]
Funny. @ryancoleman is my cousin. /me waves.

**Comment by ryanycoleman** [comment]
@ffrank I feel like I'm missing a piece of context. How's the Forge forcing that behavior?

I agree with you regarding keeping the module discrete and expecting someone to provide their own java. To me, it's a trade-off between simplicity for someone who just wants to `puppet module install` and `puppet agent -t` vs flexibility for those who want to choose which content satisfies the dependencies. 

For something as big as Atlasssian Stash, I think it's safe to expect someone to do the extra work to satisfy the dependency on java. Bonus points for including in the README docs on how to satisfy the dependency with puppetlabs-java.

**Comment by ffrank** [comment]
Oops, right - the context seems to be gone from this thread.

Here is what @mkrakowitzer had originally written (sorry Merritt if you wanted this gone ;-)

> The javahome is actually a required parameter. It used to be set
> $javahome,
> 
> But I think because that effects the puppet module scoring, I made it
> $javahome = undef,
> 
> I think I should perhaps make it

I see how a module would score lower for having loads of required parameters. But if this becomes an incentive to build horrors around artificial defaults and calls to the `fail` function, then overall quality may suffer.

**Comment by mkrakowitzer** [comment]
@ffrank no problem, after rereading your initial comment I felt I missed the mark with my response re this PR. 

I have tried to address your concerns with an updated PR.
I removed a lot of duplication in the tests and moved them to its own file, all with default params. I left the tests as is that test for the download. 
I added a new test that only concerns itself with the java path that ends up being used, given the parameter value.

**Comment by igalic** [comment]
i think puppetlabs-java's main problem, and the reason we don't use it in complex environments is: https://github.com/puppetlabs/puppetlabs-java/pull/110

**Comment by mkrakowitzer** [comment]
@igalic I don’t want to be merging my own commits? Would you be happy to merge this assuming you feel I have addressed everyones comments? and there are no other points that need to be addressed?

**Comment by igalic** [comment]
absolutely!

**Pull request merged**
