### PR TITLE
Remove uppercase parameter/variable names

### PR DESCRIPTION
**Pull request by mkrakowitzer**

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
:+1:

**Comment by igalic** [comment]
as @bastelfreak pointed out on IRC, this will require a major version bump

**Comment by daenney** [comment]
Yup. You've changed the API of the module so that's a major bump.

**Comment by mkrakowitzer** [comment]
I bumped the major version last week already :) with a huge notice banner.

**Pull request merged**
