### PR TITLE
Issue #92 - Add support for bitbucket server

### PR DESCRIPTION
**Pull request by mkrakowitzer**
Use puppet-archive to deploy stash files.
Removes the staging and deploy modules from stash module.
Update tests, readme, nodesets, fixtures, gitignore.

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
While puppet-archive is more actively developed than staging, puppet-archive does not yet support s3. I know of quite a few places that need to grab the tarball from a S3 bucket for installation rather than from the Atlassian site.

**Comment by juniorsysadmin** [comment]
Also, if this is going to be a major version bump, perhaps it would be worth fixing the camelcase variable names (incompatible with Puppet 4) and adding some additional puppet-lint gems like puppet-lint-variable_contains_upcase

**Comment by mkrakowitzer** [comment]
@juniorsysadmin noted, Will add support for the staging module again, Which do you think is most appropriate to be the default?

Re version 2.0.0, There are quite a few things that need fixing, off the top of my head.

Make sure this module works with puppet 4
Remove the camelcase parameters.
Move away from templates for the server.xml in favour of augeas.

**Comment by juniorsysadmin** [comment]
> Will add support for the staging module again, Which do you think is most appropriate to be the default?

Whichever is still being actively developed and is on the Forge, as `$enterprise` generally prefers this over something on GitHub only. Neither archive or staging has a version published under the puppet-community namespace, which is probably something we should do...

**Pull request merged**
