### PR TITLE
Pin rake to avoid rubocop/rake 11 incompatibility

### PR DESCRIPTION
**Pull request by roidelapluie**
See https://github.com/voxpupuli/modulesync_config/pull/93

This commit updates the module to our latest modulesync configuration.

### CODE REVIEW

**Comment by igalic** [comment]
are those known failures?

```
  Evaluation Error: Unknown variable: 'stash::repoforge'. at
```

**Comment by dhoppe** [comment]
@mkrakowitzer I think this was not completely removed with PR #104. I will remove this including the dependency at `metadata.json` and `spec_helper_acceptance.rb`.

**Comment by jyaworski** [comment]
Is this good to merge?

**Comment by dhoppe** [comment]
@jyaworski Please merge. ;)

**Pull request merged**
