### PR TITLE
Allow stash-config.properties to be configured using hiera

### PR DESCRIPTION
**Pull request by berthamilton**
I understand that master is undergoing a large refactor to support upgrades to bitbucket server, so I have branched a the latest release 1.3.0 to so that people may upgrade this module while they are waiting.

### CODE REVIEW

**Comment by jyaworski** [comment]
@berthamilton there are merge conflicts. Can you look?

**Comment by berthamilton** [comment]
Hi there - merge conflicts are expected as I branched at the 1.3.0 tag to make this change. I understand that master is being refactored as part of supporting bitbucket server and isn't in a stable state - so really I would want to resubmit this pull request to a maintenance branch of 1.3.x

**Comment by igalic** [comment]
@berthamilton :+1:

**Comment by ffrank** [comment]
OK, so I figure we need to create that branch...

**Comment by berthamilton** [comment]
I think this functionality has been included in
https://github.com/voxpupuli/puppet-stash/pull/86 - but was not released
when I added my own. You caa forget this pull request

**Comment by ffrank** [comment]
Hmm, I see. Still, should we see whether pulling that into a "short-term-release" branch would make sense? There might be more unreleased features in master that people need.

**Pull request closed without merging**
