### PR TITLE
Setting tidy to recurse twice

### PR DESCRIPTION
**Pull request by johnlawerance**
This fixes Issue [91](https://github.com/puppet-community/puppet-stash/issues/91)

### CODE REVIEW

**Comment by mkrakowitzer** [comment]
Thanks for this, we just have to update the tests. spec/classes/stash_backup_spec.rb:5

```
expected that the catalogue would contain Tidy[remove_old_archives] with recurse set to 1 but it is set to "2"
```

Probably best to wait until after #99 is merged otherwise we going to have one uber merge conflict on our hands.

**Comment by johnlawerance** [comment]
No worries, sounds good.

**Comment by johnlawerance** [comment]
@mkrakowitzer Fixed conflict after #99 was merged. Should be all set.

**Comment by igalic** [comment]
@johnlawerance can you [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) (and perhaps [squash](http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) too) to get rid of the merge-commit.

**Comment by johnlawerance** [comment]
Just canceling this guy out since it got nasty after the rebase merge. Created a new PR: [102](https://github.com/puppet-community/puppet-stash/pull/102)

**Pull request closed without merging**
